method: bayes
metric:
    name: val_f1
    goal: maximize
parameters:
    epochs:
        value: 2 
    learning_rate:
        min: 0.0001
        max: 0.05  
        distribution: log_uniform_values
    batch_size:
        values: [32, 64, 128]  
    input_dim:
        value: 19
    hidden_dim:
        values: [16, 32, 64, 128, 256]
    num_layers:
        values: [1, 2]
    dropout:
        values: [0.0, 0.1, 0.3]
    optimizer:
        value: "adam"
        # values: ["adam", "sgd"]
