method: random
metric:
    name: val_f1
    goal: maximize

parameters:
    seed:
        value: 1
    epochs:
        value: 200
    learning_rate:
        value: 0.001
    batch_size:
        value: 128

    input_dim:
        value: 19
    d_model:
        values: [128, 256, 512]
    nhead:
        values: [4, 8]
    num_encoder_layers:
        values: [1, 2, 3]
    dim_feedforward:
        values: [256, 512, 1024, 2048]
    dropout:
        value: 0.1
    max_seq_length:
        value: 1000

    optimizer:
        value: "adam"
